version: "3.9"

services:
  nginx_ffg_test:
    image: nginx:1.21.6
    container_name: nginx_ffg_test
    restart: always
    ports:
      - "80:8080"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../static:/opt/web/static
      - ../media:/opt/web/media
    depends_on:
      - web_ffg_test

  web_ffg_test:
    image: web_ffg_test
    container_name: web_ffg_test
    command: ./compose/base/gunicorn.sh
    build:
      context: ../
      dockerfile: ./compose/base/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../static:/opt/web/static
      - ../media:/opt/web/media
